from .construct_composed_dataset import execute_decomposition
from .kfold import KFold_cross_validation_split
from .multiclass_confusion_matrix import multiclass_confusion_matrix
from .preprocessing import preprocess_single_image, preprocess_images
from .extraction_and_metrics import extract_features, compute_confusion_matrix, compose_classes
